name: Datree CLI
description: Use the Datree CLI in a github action
author: hadarco
inputs:
  token:
    description: test
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: 'terminal'
  color: 'black'
